---
title: "R Notebook"
output: html_notebook
---
```{r message=FALSE, warning=FALSE}
library(tidyverse)
```

## AQI

```{r}
library(readr)
aqi_data0 <- read_csv("C:/Users/cmors/OneDrive/Desktop/AirBenders/aqi_daily_1980_to_2021.csv", 
    col_types = cols(Date = col_date(format = "%Y-%m-%d"), 
        Category = col_skip()))
```

```{r}
head(aqi_data0)
```

```{r}
aqi_data0 <- separate(aqi_data0, Date, into = c('Year','Month','Day'), sep = '-')

head(aqi_data0)
```


```{r}
aqi_data <- aqi_data0 %>% 
  select(Year, Month, `State Name`, Latitude, Longitude, AQI, `Defining Parameter`) %>% 
  rename(State = `State Name`) %>% 
  rename(Parameter = `Defining Parameter`) %>% 
  filter(State != 'Alaska') %>% 
  filter(State != 'Hawaii') %>% 
  filter(State != 'Country Of Mexico') %>% 
  filter(State != 'Virgin Islands') %>% 
  filter(State != 'Puerto Rico') %>% 
  group_by(Year, Month, State, Latitude, Longitude, Parameter) %>% 
  summarise(AQI = mean(AQI), .groups= 'drop')
  
head(aqi_data)
```

```{r}
#write.csv(aqi_data, 
#          'C:\\Users\\cmors\\OneDrive\\Desktop\\AirBenders\\aqi_months_coords_1117.csv')
```

```{r}
aqi <- aqi_data %>% 
  select(-c(Latitude, Longitude)) %>% 
  group_by(Year, Month, State, Parameter) %>% 
  summarise(AQI = mean(AQI), .groups = 'drop')
```





## Mortality without Ages

```{r}
mortality_months1 <- read.delim("C:/Users/cmors/OneDrive/Desktop/AirBenders/mortality_months1.txt")
mortality_months2 <- read.delim("C:/Users/cmors/OneDrive/Desktop/AirBenders/mortality_months2.txt")
```
```{r}
head(mortality_months1)
```

```{r}
clean_data <- function(data){
  new_data <- data %>% filter(Notes == '')
  new_data <- separate(new_data, Month.Code, c('Year','Month'), '/')
  new_data <- new_data %>% select(Year, Month, State, Deaths)
}
```

```{r}
data1 <- clean_data(mortality_months1)
data2 <- clean_data(mortality_months2)
```

```{r}
head(data1)
```
```{r}
table(data2$Year)
```
```{r}
data2 <- data2 %>% rename(CP_Deaths = Deaths)
```

```{r}
data_months <- merge(data1, data2) %>% 
  mutate(CP_Percent = CP_Deaths / Deaths * 100)

head(data_months)
```

## AQI + Mortality by Month

```{r}
aqi_mort_months <- left_join(aqi, data_months, by = c('Year', 'Month', 'State'))
```

```{r}
#write.csv(aqi_mort_months, 
#          'C:\\Users\\cmors\\OneDrive\\Desktop\\AirBenders\\aqi_mort_months_1117.csv')
```




# Mortality With Age Groups

```{r}
mortality_months_ages1_1 <- read.delim("C:/Users/cmors/OneDrive/Desktop/AirBenders/mortality_months_ages1_1.txt")
mortality_months_ages1_2 <- read.delim("C:/Users/cmors/OneDrive/Desktop/AirBenders/mortality_months_ages1_2.txt")
mortality_months_ages1_3 <- read.delim("C:/Users/cmors/OneDrive/Desktop/AirBenders/mortality_months_ages1_3.txt")
mortality_months_ages1_4 <- read.delim("C:/Users/cmors/OneDrive/Desktop/AirBenders/mortality_months_ages1_4.txt")
mortality_months_ages1_5 <- read.delim("C:/Users/cmors/OneDrive/Desktop/AirBenders/mortality_months_ages1_5.txt")
```

```{r}
mortality_months_ages2_1 <- read.delim("C:/Users/cmors/OneDrive/Desktop/AirBenders/mortality_months_ages2_1.txt")
mortality_months_ages2_2 <- read.delim("C:/Users/cmors/OneDrive/Desktop/AirBenders/mortality_months_ages2_2.txt")
mortality_months_ages2_3 <- read.delim("C:/Users/cmors/OneDrive/Desktop/AirBenders/mortality_months_ages2_3.txt")
mortality_months_ages2_4 <- read.delim("C:/Users/cmors/OneDrive/Desktop/AirBenders/mortality_months_ages2_4.txt")
mortality_months_ages2_5 <- read.delim("C:/Users/cmors/OneDrive/Desktop/AirBenders/mortality_months_ages2_5.txt")
```


```{r}
head(mortality_months_ages1_1)
```

```{r}
clean_ages_data <- function(data){
  new_data <- data %>% filter(Notes == '')
  new_data <- separate(new_data, Month.Code, c('Year','Month'), '/')
  new_data <- new_data %>% select(Year, Month, State, Ten.Year.Age.Groups, Deaths)
}
```

```{r}
data_ages1_1 <- clean_ages_data(mortality_months_ages1_1)
data_ages1_2 <- clean_ages_data(mortality_months_ages1_2)
data_ages1_3 <- clean_ages_data(mortality_months_ages1_3)
data_ages1_4 <- clean_ages_data(mortality_months_ages1_4)
data_ages1_5 <- clean_ages_data(mortality_months_ages1_5)
```
```{r}
data_ages1 <- rbind(data_ages1_1, data_ages1_2, 
                    data_ages1_3, data_ages1_4,
                    data_ages1_5)
```
```{r}
table(data_ages1$Year)
```
```{r}
data_ages1
```


```{r}
clean_ages_data2 <- function(data){
  new_data <- data %>% filter(Notes == '')
  new_data <- separate(new_data, Month.Code, c('Year','Month'), '/')
  new_data <- new_data %>% select(Year, Month, State, Ten.Year.Age.Groups, Deaths) %>% 
    rename(CP_Deaths = Deaths)
}
```

```{r}
data_ages2_1 <- clean_ages_data2(mortality_months_ages2_1)
data_ages2_2 <- clean_ages_data2(mortality_months_ages2_2)
data_ages2_3 <- clean_ages_data2(mortality_months_ages2_3)
data_ages2_4 <- clean_ages_data2(mortality_months_ages2_4)
data_ages2_5 <- clean_ages_data2(mortality_months_ages2_5)
```
```{r}
data_ages2 <- rbind(data_ages2_1, data_ages2_2, 
                    data_ages2_3, data_ages2_4,
                    data_ages2_5)
```
```{r}
table(data_ages2$Year)
```
```{r}
data_ages2
```


```{r}
data_ages <- left_join(data_ages1, data_ages2, by = c('Year', 'Month', 'State', 'Ten.Year.Age.Groups'))

head(data_ages)
```
```{r}
table(data_ages$Year)
```

```{r}
data_ages[which(data_ages$CP_Deaths > data_ages$Deaths), ]
```
```{r}
data_ages <- data_ages %>% 
  mutate(CP_Deaths = replace_na(CP_Deaths, 0),
         CP_Percent = CP_Deaths / Deaths * 100)
```

```{r}
aqi_mort_months_ages <- left_join(aqi, data_ages, by = c('Year', 'Month', 'State'))
```

```{r}
#write.csv(aqi_mort_months_ages, 
#          'C:\\Users\\cmors\\OneDrive\\Desktop\\AirBenders\\aqi_mort_months_ages_1117.csv')
```



```{r}
youths <- aqi_mort_months_ages %>% 
  filter(Ten.Year.Age.Groups != '85+ years') %>% 
  filter(Ten.Year.Age.Groups != '75-84 years') %>% 
  mutate(Pct_CP = CP_Deaths / Deaths * 100)
```
```{r}
head(youths)
```


```{r}
youths %>% ggplot(aes(x = Ten.Year.Age.Groups, y = CP_Percent)) + 
  geom_boxplot()
```

```{r}
comps <- aqi_mort_months_ages %>% 
  mutate(AQI_cat = ifelse(AQI > 80, '>80',
                      ifelse(AQI > 70, '71-80',
                             ifelse(AQI > 60, '61-70',
                                    ifelse(AQI > 50, '51-60',
                                           ifelse(AQI > 40, '41-50', '< 40')))))) %>% 
  mutate(AQI_cat = factor(AQI_cat, levels = c('< 40','41-50','51-60','61-70','71-80','>80')))

head(comps[comps$Year == '1999', ])
```

```{r}
table(comps$AQI_cat)
```
```{r}
comps %>% 
  filter(!is.na(CP_Percent)) %>% 
  group_by(AQI_cat) %>% 
  summarise(CP_Percent = mean(CP_Percent), .groups = 'drop')
```

```{r}
library(car)
```

```{r}
anova1 <- aov(CP_Percent ~ AQI_cat, data = comps %>% filter(!is.na(CP_Percent)))
summary(anova1)
```
```{r}
tukey1 <- TukeyHSD(anova1)
tukey1
```
```{r}
tukey1$AQI_cat[tukey1$AQI_cat[,4] < 0.05, ]
```
** Very good air quality is associated with higher rates of cardiopulmonary deaths.


```{r}
comps %>% 
  filter(!is.na(CP_Percent)) %>% 
  filter((Ten.Year.Age.Groups == '85+ years')|(Ten.Year.Age.Groups == '75-84 years')) %>% 
  group_by(AQI_cat) %>% 
  summarise(CP_Percent = mean(CP_Percent), .groups = 'drop')
```
```{r}
library(ggpubr)
```

```{r}
hist80 <- comps %>% 
  filter(Ten.Year.Age.Groups == '85+ years') %>% 
  filter(AQI_cat == '>80') %>% 
  ggplot(aes(CP_Percent)) + 
  theme_bw() +
  geom_histogram(bins = 25, fill = 'navyblue', color = 'goldenrod') + 
  labs(title = 'AQI > 80',
       x = 'Percent CP Deaths')

hist70 <- comps %>% 
  filter(Ten.Year.Age.Groups == '85+ years') %>% 
  filter(AQI_cat == '71-80') %>% 
  ggplot(aes(CP_Percent)) + 
  theme_bw() +
  geom_histogram(bins = 25, fill = 'navyblue', color = 'goldenrod') + 
  labs(title = '71-80',
       x = 'Percent CP Deaths')

hist60 <- comps %>% 
  filter(Ten.Year.Age.Groups == '85+ years') %>% 
  filter(AQI_cat == '61-70') %>% 
  ggplot(aes(CP_Percent)) + 
  theme_bw() +
  geom_histogram(bins = 25, fill = 'navyblue', color = 'goldenrod') + 
  labs(title = '61-70',
       x = 'Percent CP Deaths')

hist50 <- comps %>% 
  filter(Ten.Year.Age.Groups == '85+ years') %>% 
  filter(AQI_cat == '51-60') %>% 
  ggplot(aes(CP_Percent)) + 
  theme_bw() +
  geom_histogram(bins = 25, fill = 'navyblue', color = 'goldenrod') + 
  labs(title = 'AQI 51-60',
       x = 'Percent CP Deaths')

hist40 <- comps %>% 
  filter(Ten.Year.Age.Groups == '85+ years') %>% 
  filter(AQI_cat == '41-50') %>% 
  ggplot(aes(CP_Percent)) + 
  theme_bw() +
  geom_histogram(bins = 25, fill = 'navyblue', color = 'goldenrod') + 
  labs(title = 'AQI 41-50',
       x = 'Percent CP Deaths')

hist30 <- comps %>% 
  filter(Ten.Year.Age.Groups == '85+ years') %>% 
  filter(AQI_cat == '< 40') %>% 
  ggplot(aes(CP_Percent)) + 
  theme_bw() +
  geom_histogram(bins = 25, fill = 'navyblue', color = 'goldenrod') + 
  labs(title = 'AQI < 40',
       x = 'Percent CP Deaths')

plot <- ggarrange(hist30, hist40, hist50, hist60, hist70, hist80,
                  ncol = 3, nrow = 2)
annotate_figure(plot, top = 'CP Deaths for People > 85 Years Old')
```





```{r}
anova2 <- aov(CP_Percent ~ AQI_cat, data = comps %>% filter(!is.na(CP_Percent)) %>% 
  filter(Ten.Year.Age.Groups == '85+ years'))
summary(anova2)
```
```{r}
tukey2 <- TukeyHSD(anova2)
```
```{r}
tukey2$AQI_cat[tukey2$AQI_cat[,4] < 0.05, ]
```

```{r}
anova3 <- aov(CP_Percent ~ AQI_cat, data = comps %>% filter(!is.na(CP_Percent)) %>% 
  filter(Ten.Year.Age.Groups == '75-84 years'))
summary(anova3)
```
```{r}
tukey3 <- TukeyHSD(anova3)
tukey3$AQI_cat[tukey3$AQI_cat[,4] < 0.05, ]
```




```{r}
anova4 <- aov(CP_Percent ~ AQI_cat, data = comps %>% filter(!is.na(CP_Percent)) %>% 
  filter(Ten.Year.Age.Groups == '65-74 years'))
summary(anova4)
```
```{r}
tukey4 <- TukeyHSD(anova4)
tukey4$AQI_cat[tukey4$AQI_cat[,4] < 0.05, ]
```



```{r}
anova5 <- aov(CP_Percent ~ AQI_cat, data = comps %>% filter(!is.na(CP_Percent)) %>% 
  filter(Ten.Year.Age.Groups == '55-64 years'))
summary(anova5)
```
```{r}
tukey5 <- TukeyHSD(anova5)
tukey5$AQI_cat[tukey5$AQI_cat[,4] < 0.05, ]
```


```{r}
anova6 <- aov(CP_Percent ~ AQI_cat, data = comps %>% filter(!is.na(CP_Percent)) %>% 
  filter(Ten.Year.Age.Groups == '45-54 years'))
summary(anova6)
```
```{r}
tukey6 <- TukeyHSD(anova6)
tukey6$AQI_cat[tukey6$AQI_cat[,4] < 0.05, ]
```





```{r}
anova7 <- aov(CP_Percent ~ AQI_cat, data = comps %>% filter(!is.na(CP_Percent)) %>% 
  filter(Ten.Year.Age.Groups == '35-44 years'))
summary(anova7)
```
```{r}
tukey7 <- TukeyHSD(anova7)
tukey7$AQI_cat[tukey7$AQI_cat[,4] < 0.05, ]
```




```{r}
anova8 <- aov(CP_Percent ~ AQI_cat, data = comps %>% filter(!is.na(CP_Percent)) %>% 
  filter(Ten.Year.Age.Groups == '25-34 years'))
summary(anova8)
```
```{r}
tukey8 <- TukeyHSD(anova8)
tukey8$AQI_cat[tukey8$AQI_cat[,4] < 0.05, ]
```




```{r}
anova9 <- aov(CP_Percent ~ AQI_cat, data = comps %>% filter(!is.na(CP_Percent)) %>% 
  filter(Ten.Year.Age.Groups == '15-24 years'))
summary(anova9)
```
```{r}
tukey9 <- TukeyHSD(anova9)
tukey9$AQI_cat[tukey9$AQI_cat[,4] < 0.05, ]
```




```{r}
anova10 <- aov(CP_Percent ~ AQI_cat, data = comps %>% filter(!is.na(CP_Percent)) %>% 
  filter(Ten.Year.Age.Groups == '5-14 years'))
summary(anova10)
```
```{r}
tukey10 <- TukeyHSD(anova10)
tukey10$AQI_cat[tukey10$AQI_cat[,4] < 0.05, ]
```



```{r}
anova11 <- aov(CP_Percent ~ AQI_cat, data = comps %>% filter(!is.na(CP_Percent)) %>% 
  filter(Ten.Year.Age.Groups == '1-4 years'))
summary(anova11)
```
```{r}
tukey11 <- TukeyHSD(anova11)
tukey11$AQI_cat[tukey11$AQI_cat[,4] < 0.05, ]
```



```{r}
anova12 <- aov(CP_Percent ~ AQI_cat, data = comps %>% filter(!is.na(CP_Percent)) %>% 
  filter(Ten.Year.Age.Groups == '< 1 year'))
summary(anova12)
```
```{r}
tukey12 <- TukeyHSD(anova12)
tukey12$AQI_cat[tukey12$AQI_cat[,4] < 0.05, ]
```


```{r}
comps %>% 
  filter(Ten.Year.Age.Groups == '85+ years') %>% 
  mutate(AQI_cat = factor(AQI_cat, levels = c('>80','71-80','61-70','51-60','41-50','< 40'))) %>% 
  ggplot(aes(x = AQI_cat, y = CP_Percent)) + 
  geom_boxplot(fill = 'navyblue', color = 'goldenrod') +
  theme_bw() +
  labs(title = 'Percentage CP Deaths per AQI score: ages 85+',
       x = 'AQI Category',
       y = 'Percentage of Deaths with CP Diagnosis')
```



```{r}
comps %>% 
  filter(Ten.Year.Age.Groups == '85+ years') %>% 
  filter(Parameter == 'CO') %>% 
  mutate(AQI_cat = factor(AQI_cat, levels = c('>80','71-80','61-70','51-60','41-50','< 40'))) %>% 
  ggplot(aes(x = AQI_cat, y = CP_Percent)) + 
  geom_boxplot(fill = 'navyblue', color = 'goldenrod') +
  theme_bw() +
  labs(title = 'Percentage CP Deaths per CO-AQI category: ages 85+',
       x = 'CO AQI Category',
       y = 'Percentage of Deaths with CP Diagnosis')
```
```{r}
comps %>% 
  filter(Ten.Year.Age.Groups == '85+ years') %>% 
  filter(Parameter == 'SO2') %>% 
  mutate(AQI_cat = factor(AQI_cat, levels = c('>80','71-80','61-70','51-60','41-50','< 40'))) %>% 
  ggplot(aes(x = AQI_cat, y = CP_Percent)) + 
  geom_boxplot(fill = 'navyblue', color = 'goldenrod') +
  theme_bw() +
  labs(title = 'Percentage CP Deaths per NO2-AQI category: ages 85+',
       x = 'NO2 AQI Category',
       y = 'Percentage of Deaths with CP Diagnosis')
```
```{r}
comps %>% 
  filter(Ten.Year.Age.Groups == '85+ years') %>% 
  filter(Parameter == 'NO2') %>% 
  mutate(AQI_cat = factor(AQI_cat, levels = c('>80','71-80','61-70','51-60','41-50','< 40'))) %>% 
  ggplot(aes(x = AQI_cat, y = CP_Percent)) + 
  geom_boxplot(fill = 'navyblue', color = 'goldenrod') +
  theme_bw() +
  labs(title = 'Percentage CP Deaths per NO2-AQI category: ages 85+',
       x = 'NO2 AQI Category',
       y = 'Percentage of Deaths with CP Diagnosis')
```


```{r}
comps %>% 
  filter(Ten.Year.Age.Groups == '85+ years') %>% 
  filter(Parameter == 'Ozone') %>% 
  mutate(AQI_cat = factor(AQI_cat, levels = c('>80','71-80','61-70','51-60','41-50','< 40'))) %>% 
  ggplot(aes(x = AQI_cat, y = CP_Percent)) + 
  geom_boxplot(fill = 'navyblue', color = 'goldenrod') +
  theme_bw() +
  labs(title = 'Percentage CP Deaths per Ozone-AQI category: ages 85+',
       x = 'NO2 AQI Category',
       y = 'Percentage of Deaths with CP Diagnosis')
```
```{r}
comps %>% 
  filter(Ten.Year.Age.Groups == '85+ years') %>% 
  filter(Parameter == 'PM2.5') %>% 
  mutate(AQI_cat = factor(AQI_cat, levels = c('>80','71-80','61-70','51-60','41-50','< 40'))) %>% 
  ggplot(aes(x = AQI_cat, y = CP_Percent)) + 
  geom_boxplot(fill = 'navyblue', color = 'goldenrod') +
  theme_bw() +
  labs(title = 'Percentage CP Deaths per PM 2.5-AQI category: ages 85+',
       x = 'NO2 AQI Category',
       y = 'Percentage of Deaths with CP Diagnosis')
```
```{r}
comps %>% 
  filter(Ten.Year.Age.Groups == '85+ years') %>% 
  filter(Parameter == 'PM10') %>% 
  mutate(AQI_cat = factor(AQI_cat, levels = c('>80','71-80','61-70','51-60','41-50','< 40'))) %>% 
  ggplot(aes(x = AQI_cat, y = CP_Percent)) + 
  geom_boxplot(fill = 'navyblue', color = 'goldenrod') +
  theme_bw() +
  labs(title = 'Percentage CP Deaths per PM 2.5-AQI category: ages 85+',
       x = 'NO2 AQI Category',
       y = 'Percentage of Deaths with CP Diagnosis')
```



```{r}
comps[as.integer(comps$Year) >= 1999, ]
```



```{r}
comps %>% 
  group_by(Ten.Year.Age.Groups, AQI_cat) %>% 
  summarise(CP_Percent = mean(CP_Percent), .groups = 'drop')
```





```{r}
comps2 <- aqi_mort_months_ages %>% 
  mutate(AQI_cat = ifelse(AQI > 80, '>80',
                          ifelse(AQI > 75, '76-80',
                                 ifelse(AQI > 70, '71-75',
                                        ifelse(AQI > 65, '66-70',
                                               ifelse(AQI > 60, '61-65',
                                                      ifelse(AQI > 55, '56-60',
                                                             ifelse(AQI > 50, '51-55',
                                                                    ifelse(AQI > 45, '46-50',
                                                                           ifelse(AQI > 40, '41-45',
                                                                                  ifelse(AQI > 35, '36-40',
                                                                                         ifelse(AQI > 30, '31-35', '30 or less')))))))))))) %>% 

  mutate(AQI_cat = factor(AQI_cat, levels = c('>80', '76-80', '71-75',
                                              '66-70', '61-65', '56-60',
                                              '51-55', '46-50', '41-45', 
                                              '36-40', '30 or less'))) %>% 
  filter(Ten.Year.Age.Groups != 'Not Stated') %>% 
  filter(!is.na(Ten.Year.Age.Groups)) %>% 
  mutate(Ten.Year.Age.Groups = factor(Ten.Year.Age.Groups, levels = c('< 1 year',
                                                                      '1-4 years',
                                                                      '5-14 years',
                                                                      '15-24 years',
                                                                      '25-34 years',
                                                                      '35-44 years',
                                                                      '45-54 years',
                                                                      '55-64 years',
                                                                      '65-74 years',
                                                                      '75-84 years',
                                                                      '85+ years')))

head(comps2[comps2$Year == '1999', ])
```

```{r}
comps2 %>% 
  filter(!is.na(AQI_cat)) %>% 
  group_by(Ten.Year.Age.Groups, AQI_cat) %>% 
  summarise(CP_Percent = mean(CP_Percent), .groups = 'drop')
```



```{r}
comps2 %>% 
  filter(!is.na(AQI_cat)) %>% 
  ggplot(aes(x = Ten.Year.Age.Groups, y = CP_Percent, color = AQI_cat)) + 
  geom_point(position = 'jitter') + 
  theme_bw() + 
  scale_color_brewer('AQI Score', palette = 'RdYlBu') + 
  labs(title = 'Cardiopulmonary Mortality Across Age Groups',
       x = 'Age',
       y = 'Percent Deaths with Cardiopulmonary Cause')
```
```{r}
#library(viridis)
```


```{r}
plot_total <- comps2 %>% 
  filter(!is.na(AQI_cat)) %>% 
  group_by(Ten.Year.Age.Groups, Year) %>% 
  summarise(CP_Percent = mean(CP_Percent), 
            AQI = mean(AQI),
            .groups = 'drop') %>% 
  ggplot(aes(x = CP_Percent, y = Ten.Year.Age.Groups, color = AQI)) + 
  geom_point(position = position_jitterdodge()) + 
  theme_bw() + 
  scale_color_viridis_c('AQI Score', direction = -1) + 
  labs(title = 'Total AQI Score',
       x = 'Percent Deaths with Cardiopulmonary Cause',
       y = 'Age')

plot_total
```
```{r}
plot_co <- comps2 %>% 
  filter(!is.na(AQI_cat)) %>% 
  filter(Parameter == 'CO') %>% 
  group_by(Ten.Year.Age.Groups, Year) %>% 
  summarise(CP_Percent = mean(CP_Percent), 
            AQI = mean(AQI),
            .groups = 'drop') %>% 
  ggplot(aes(x = CP_Percent, y = Ten.Year.Age.Groups, color = AQI)) + 
  geom_point(position = position_jitterdodge()) + 
  theme_bw() + 
  scale_color_viridis_c('CO AQI Score', direction = -1) + 
  labs(title = 'Carbon Monoxide',
       x = 'Percent Deaths with Cardiopulmonary Cause',
       y = 'Age')

plot_no2 <- comps2 %>% 
  filter(!is.na(AQI_cat)) %>% 
  filter(Parameter == 'NO2') %>% 
  group_by(Ten.Year.Age.Groups, Year) %>% 
  summarise(CP_Percent = mean(CP_Percent), 
            AQI = mean(AQI),
            .groups = 'drop') %>% 
  ggplot(aes(x = CP_Percent, y = Ten.Year.Age.Groups, color = AQI)) + 
  geom_point(position = position_jitterdodge()) + 
  theme_bw() + 
  scale_color_viridis_c('NO2 AQI Score', direction = -1) + 
  labs(title = 'Nitrogen Dioxide',
       x = 'Percent Deaths with Cardiopulmonary Cause',
       y = 'Age')

plot_so2 <- comps2 %>% 
  filter(!is.na(AQI_cat)) %>% 
  filter(Parameter == 'SO2') %>% 
  group_by(Ten.Year.Age.Groups, Year) %>% 
  summarise(CP_Percent = mean(CP_Percent), 
            AQI = mean(AQI),
            .groups = 'drop') %>% 
  ggplot(aes(x = CP_Percent, y = Ten.Year.Age.Groups, color = AQI)) + 
  geom_point(position = position_jitterdodge()) + 
  theme_bw() + 
  scale_color_viridis_c('SO2 AQI Score', direction = -1) + 
  labs(title = 'Sulfur Dioxide',
       x = 'Percent Deaths with Cardiopulmonary Cause',
       y = 'Age')

plot_ozone <- comps2 %>% 
  filter(!is.na(AQI_cat)) %>% 
  filter(Parameter == 'Ozone') %>% 
  group_by(Ten.Year.Age.Groups, Year) %>% 
  summarise(CP_Percent = mean(CP_Percent), 
            AQI = mean(AQI),
            .groups = 'drop') %>% 
  ggplot(aes(x = CP_Percent, y = Ten.Year.Age.Groups, color = AQI)) + 
  geom_point(position = position_jitterdodge()) + 
  theme_bw() + 
  scale_color_viridis_c('Ozone AQI Score', direction = -1) + 
  labs(title = 'Ozone',
       x = 'Percent Deaths with Cardiopulmonary Cause',
       y = 'Age')

plot_pm10 <- comps2 %>% 
  filter(!is.na(AQI_cat)) %>% 
  filter(Parameter == 'PM10') %>% 
  group_by(Ten.Year.Age.Groups, Year) %>% 
  summarise(CP_Percent = mean(CP_Percent), 
            AQI = mean(AQI),
            .groups = 'drop') %>% 
  ggplot(aes(x = CP_Percent, y = Ten.Year.Age.Groups, color = AQI)) + 
  geom_point(position = position_jitterdodge()) + 
  theme_bw() + 
  scale_color_viridis_c('PM-10 AQI Score', direction = -1) + 
  labs(title = 'Particulate Matter 10',
       x = 'Percent Deaths with Cardiopulmonary Cause',
       y = 'Age')

plot_pm2.5 <- comps2 %>% 
  filter(!is.na(AQI_cat)) %>% 
  filter(Parameter == 'PM2.5') %>% 
  group_by(Ten.Year.Age.Groups, Year) %>% 
  summarise(CP_Percent = mean(CP_Percent), 
            AQI = mean(AQI),
            .groups = 'drop') %>% 
  ggplot(aes(x = CP_Percent, y = Ten.Year.Age.Groups, color = AQI)) + 
  geom_point(position = position_jitterdodge()) + 
  theme_bw() + 
  scale_color_viridis_c('PM-2.5 AQI Score', direction = -1) + 
  labs(title = 'Particulate Matter 2.5',
       x = 'Percent Deaths with Cardiopulmonary Cause',
       y = 'Age')
```

```{r}
plot <- ggarrange(plot_total, plot_co, plot_no2, plot_so2, 
                  plot_ozone, plot_pm10, plot_pm2.5,
                  ncol = 4, nrow = 2)

annotate_figure(plot, top = text_grob('Cardiopulmonary Mortality Across Age Groups',
                                      color = 'navyblue', face = 'bold'))
```


```{r}
comps2
```

```{r}
table(comps2$Parameter)
```















